version: '3'
services:
  redis:
    build:
      context: .
      dockerfile: ./redis/Dockerfile
    ports:
      - "6379:6379"
    command: redis-server /usr/local/conf/redis.conf --appendonly yes
    volumes:
      - redis-data:/data
  node:
    build:
      context: .
      dockerfile: ./node/Dockerfile
    ports:
      - "3912:3000"
    volumes:
      - ./backend:/app
    links:
      - redis

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "30300:80"
    volumes:
      - ./frontend:/app
    links:
      - node

volumes:
  redis-data:
    driver: local